//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Westwind.Webstore.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebStoreBusinessResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebStoreBusinessResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Westwind.Webstore.Business.Properties.WebStoreBusinessResources", typeof(WebStoreBusinessResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        internal static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This card is expired.
        /// </summary>
        internal static string CardIsExpired {
            get {
                return ResourceManager.GetString("CardIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Processing failed..
        /// </summary>
        internal static string CardProcessingFailed {
            get {
                return ResourceManager.GetString("CardProcessingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVED.
        /// </summary>
        internal static string CC_Approved {
            get {
                return ResourceManager.GetString("CC_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTHORIZED.
        /// </summary>
        internal static string CC_Authorized {
            get {
                return ResourceManager.GetString("CC_Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLINED.
        /// </summary>
        internal static string CC_Declined {
            get {
                return ResourceManager.GetString("CC_Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED.
        /// </summary>
        internal static string CC_Failed {
            get {
                return ResourceManager.GetString("CC_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete lineitem..
        /// </summary>
        internal static string CouldntDeleteLineItem {
            get {
                return ResourceManager.GetString("CouldntDeleteLineItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description can&apos;t be left empty.
        /// </summary>
        internal static string DescriptionCantBeEmpty {
            get {
                return ResourceManager.GetString("DescriptionCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Description must be at least 20 characters long.
        /// </summary>
        internal static string DetailDescriptionMustBe20CharactersLong {
            get {
                return ResourceManager.GetString("DetailDescriptionMustBe20CharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address doesn&apos;t exist.
        /// </summary>
        internal static string Email_address_doesn_t_exist {
            get {
                return ResourceManager.GetString("Email address doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is already in use. Please log into your existing account..
        /// </summary>
        internal static string EmailAddressAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAddressAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        internal static string EmailAddressIsInvalid {
            get {
                return ResourceManager.GetString("EmailAddressIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email address is required.
        /// </summary>
        internal static string EmailAddressRequired {
            get {
                return ResourceManager.GetString("EmailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation sent.
        /// </summary>
        internal static string EmailConfirmationSent {
            get {
                return ResourceManager.GetString("EmailConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailDoesntExist.
        /// </summary>
        internal static string EmailDoesntExist {
            get {
                return ResourceManager.GetString("EmailDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email failure.
        /// </summary>
        internal static string EmailFailure {
            get {
                return ResourceManager.GetString("EmailFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset password.
        /// </summary>
        internal static string FailedToResetPassword {
            get {
                return ResourceManager.GetString("FailedToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory is insufficient for item {0}. Available: {1}.
        /// </summary>
        internal static string InsufficientInventory {
            get {
                return ResourceManager.GetString("InsufficientInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credit Card Number.
        /// </summary>
        internal static string InvalidCreditCardNumber {
            get {
                return ResourceManager.GetString("InvalidCreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credit Card CardProcessor or CardProcessor not supported.
        /// </summary>
        internal static string InvalidCreditCardProcessor {
            get {
                return ResourceManager.GetString("InvalidCreditCardProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Expiration Date.
        /// </summary>
        internal static string InvalidExpirationDate {
            get {
                return ResourceManager.GetString("InvalidExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login information..
        /// </summary>
        internal static string InvalidLoginInformation {
            get {
                return ResourceManager.GetString("InvalidLoginInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Password format: Minimum of 8 characters, 1 upper, 1 lower and 1 digit are required..
        /// </summary>
        internal static string InvalidPasswordFormat {
            get {
                return ResourceManager.GetString("InvalidPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sku - this Sku exists already. Please pick another..
        /// </summary>
        internal static string InvalidSkuSkuExistsAlready {
            get {
                return ResourceManager.GetString("InvalidSkuSkuExistsAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} failed to confirm. Email Failure..
        /// </summary>
        internal static string ItemFailedToConfirm {
            get {
                return ResourceManager.GetString("ItemFailedToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either Company or Name must be entered.
        /// </summary>
        internal static string NameOrCompanyMustBeEntered {
            get {
                return ResourceManager.GetString("NameOrCompanyMustBeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lineitems to send confirmations to..
        /// </summary>
        internal static string NoLineItemsToConfirm {
            get {
                return ResourceManager.GetString("NoLineItemsToConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No partial quantities are allowed. Please use a whole number..
        /// </summary>
        internal static string NoPartialQuantitiesAllowed {
            get {
                return ResourceManager.GetString("NoPartialQuantitiesAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order was already processed..
        /// </summary>
        internal static string OrderAlreadyProcessed {
            get {
                return ResourceManager.GetString("OrderAlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order amount can&apos;t be zero..
        /// </summary>
        internal static string OrderAmountCantBeZero {
            get {
                return ResourceManager.GetString("OrderAmountCantBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Confirmation.
        /// </summary>
        internal static string OrderConfirmation {
            get {
                return ResourceManager.GetString("OrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose your primary development environment.
        /// </summary>
        internal static string PleaseChooseYourPrimaryDevelopmentEnvironment {
            get {
                return ResourceManager.GetString("PleaseChooseYourPrimaryDevelopmentEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country.
        /// </summary>
        internal static string PleaseSelectACountry {
            get {
                return ResourceManager.GetString("PleaseSelectACountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US and Canada - Please select a state.
        /// </summary>
        internal static string PleaseSelectAState {
            get {
                return ResourceManager.GetString("PleaseSelectAState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select how you found us.
        /// </summary>
        internal static string PleaseSelectHowYouFoundUs {
            get {
                return ResourceManager.GetString("PleaseSelectHowYouFoundUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code can&apos;t be empty.
        /// </summary>
        internal static string PostalCodeCantBeEmpty {
            get {
                return ResourceManager.GetString("PostalCodeCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing error.
        /// </summary>
        internal static string ProcessingError {
            get {
                return ResourceManager.GetString("ProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A shipping address is required.
        /// </summary>
        internal static string ShippingAddressRequired {
            get {
                return ResourceManager.GetString("ShippingAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Shipping City is required.
        /// </summary>
        internal static string ShippingCityRequired {
            get {
                return ResourceManager.GetString("ShippingCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A shipping country is required.
        /// </summary>
        internal static string ShippingCountryRequired {
            get {
                return ResourceManager.GetString("ShippingCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Shipping Name or Company is required.
        /// </summary>
        internal static string ShippingNameOrCompanyRequired {
            get {
                return ResourceManager.GetString("ShippingNameOrCompanyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Shipping Postal Code is required.
        /// </summary>
        internal static string ShippingPostalCodeRequired {
            get {
                return ResourceManager.GetString("ShippingPostalCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Shipping State is required.
        /// </summary>
        internal static string ShippingStateRequired {
            get {
                return ResourceManager.GetString("ShippingStateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skus cannot contain an &amp; character..
        /// </summary>
        internal static string SkuCannotContainAmpersand {
            get {
                return ResourceManager.GetString("SkuCannotContainAmpersand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sku must be filled in..
        /// </summary>
        internal static string SkuMustBeFilledIn {
            get {
                return ResourceManager.GetString("SkuMustBeFilledIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State must be provided.
        /// </summary>
        internal static string StateCodeMustBeProvided {
            get {
                return ResourceManager.GetString("StateCodeMustBeProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to confirm item with vendor.
        /// </summary>
        internal static string UnableToConfirmItemWithVendor {
            get {
                return ResourceManager.GetString("UnableToConfirmItemWithVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Confirmation for.
        /// </summary>
        internal static string VendorConfirmationFor {
            get {
                return ResourceManager.GetString("VendorConfirmationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to provide a valid billing postal or zip code..
        /// </summary>
        internal static string YouMustProvideAValidPostalCode {
            get {
                return ResourceManager.GetString("YouMustProvideAValidPostalCode", resourceCulture);
            }
        }
    }
}
